apiVersion: v1
kind: Service
metadata:
  name: gradio-service
spec:
  type: NodePort
  selector:
    app: gradio
    tier: frontend
  ports:
  - protocol: TCP
    port: 7860
    targetPort: 7860
    # NodePort will be automatically assigned in range 30000-32767
